- hosts: all
  name: Fujihalab-system用の環境構築
  sudo: yes
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: node.jsのインストール
      yum: name"{{ item.name }}" state=present enablerepo=epel
      with_items:
        - { name: nodejs}
        - { name: npm}
