- hosts: all
  name: Fujihalab-system用の環境構築
  sudo: yes
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: setup ruby
      git:
        repo: https://github.com/sstephenson/rbenv.git
        dest: /usr/local/rbenv

    - name: 'rbenvのshファイルを配置'
      copy:
        src: templates/rbenv_system.sh
        dest: /etc/profile.d/rbenv.sh
        owner: root
        group: root
        mode: 0755

    - name: 'ruby-buildインストール'
      git:
        repo: https://github.com/sstephenson/ruby-build.git
        dest: /usr/local/rbenv/plugins/ruby-build

    - name: 'rubyインストール'
      shell: bash -lc ". /etc/profile.d/rbenv.sh &&rbenv rehash &rbenv install --skip-existing 2.6.0"

    - name: 'globalセット'
      shell: bash -lc "rbenv global 2.6.0"

    - name: 'bundlerインストール'
      gem:
        name: bundler
        user_install: no
        executable: /usr/local/rbenv/shims/gem
