- hosts: all
  name: Fujihalab-system用の環境構築
  sudo: yes
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: Setup default git configuraiton
      git_config:
        name="{{ item.name }}"
        scope=global
        value="{{ item.value }}"
      with_items:
        - {name: "user.name",  value: "fujihalaboy" }
        - {name: "user.email", value: "fujiharabotaroh@gmail.com" }
        - {name: "ui.color",   value: "True" }

    - name: ssh configにgithubの設定を追記
      blockinfile:
        dest: /home/ec2-user/.ssh/config
        create: yes
        block: |
          Host github github.com
            Hostname github.com
            User git
            IdentityFile ~/.ssh/id_rsa

    - name: .ssh/configの権限変更
      file:
        dest: /home/ec2-user/.ssh/config
        mode: 600

