- hosts: all
  name: Fujihalab-system用の環境構築
  sudo: yes
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: Setup default git configuraiton
      git_config:
        name="{{ item.name }}"
        scope=global
        value="{{ item.value }}"
      with_items:
        - {name: "user.name",  value: "fujihalaboy" }
        - {name: "user.email", value: "fujiharabotaroh@gmail.com" }
        - {name: "ui.color",   value: "True" }
        - {name: "InsteadOf",  value: "https://github.com/"}
