- hosts: all
  name: Fujihalab-system用の環境構築
  sudo: yes
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: add git ssh
      -
    - name: Setup fujihalab-system repo
      git:
        repo: https://github.com/2357gi/fujihalab-system.git
        dest: /var/www/fujihalab-system



