- hosts: all
  name: Fujihalab-system用の環境構築
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: setup nginx
      sudo: yes
      yum: name=nginx state=present

    - name: "nginx 設定ファイルの設置"
      sudo: yes
      copy: src=templates/fujihalab-system.conf
        dest=/etc/nginx/conf.d/nginx.conf

    - name: nginxの権限変更
      sudo: yes
      shell: sudo chmod -R 775 /var/lib/nginx


    - name: nginxの起動
      sudo: yes
      shell: systemctl start nginx